<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>puhu</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Puhu.Plugin\Puhu.Plugin.csproj" />
    <ProjectReference Include="..\Puhu.Marketplace\Puhu.Marketplace.csproj" />
    <ProjectReference Include="..\Puhu.Settings\Puhu.Settings.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Akka.Logger.Serilog" />
    <PackageReference Include="Akka.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Servus" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Themes\**\*.theme" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Puhu.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
