<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Puhu.Plugin.Marketplace\Puhu.Plugin.Marketplace.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Akka.Hosting.TestKit" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
</Project>
