<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Akka.Hosting" Version="1.5.68" />
    <PackageVersion Include="Akka.Logger.Serilog" Version="1.5.67" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageVersion Include="R3" Version="1.3.1" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="Servus" Version="0.34.0" />
  </ItemGroup>
  <ItemGroup Label="Testing">
    <PackageVersion Include="Akka.Hosting.TestKit" Version="1.5.68" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.6.0" />
  </ItemGroup>
  <ItemGroup Label="Transitive Pins">
    <PackageVersion Include="OpenTelemetry.Api" Version="1.16.0" />
  </ItemGroup>
</Project>
