name: Build & Test

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".github/workflows/release.yml"
      - ".github/workflows/commitlint.yml"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  GLOBAL_JSON_PATH: "./src/global.json"
  SOLUTION_PATH: "./src/Puhu.slnx"

permissions:
  contents: read
  checks: write

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} -c Release --no-restore

      - name: Test
        working-directory: ./src
        run: dotnet test --solution Puhu.slnx -c Release --no-build
        timeout-minutes: 5
